# print("How old are you?", end=' ')
# age = input()
# print("How tall are you?", end=' ')
# height = input()
# print("How much do you weigh?", end=' ')
# weight = input()

# print(f"So, you're {age} old, {height} tall and {weight} heavy.")

print("What is your first name?")
first_name = input()
print("What is your last name?")
last_name = input()
print(f"Hello, {first_name} {last_name}. How are you today?")
day_mood = input()
print(f"{first_name} {last_name}. Hopefully since your day is {day_mood} it will only get better.")
